language: node_js
node_js:
- 12

script: npm test

jobs:
  include:
    - stage: Produce Coverage
      node_js: 12
      script: npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage